### ISSUE TITLE
Question: Redirects just working on 404 routes?

### ISSUE THREAD

**Issue by AndreKelling** [venveo/craft-redirect#53]
Is it so that a redirect just works on 404 not found route?

I was just testing your wunderful plugin on an existing route.
But that didn't work.
A redirect didn't happen.

What i found was this post https://craftcms.stackexchange.com/a/21201/11140 about this topic.
Which brought me up to the idea to test with a 404 route.
And that worked.

That's not quite clear from in the readme documentation.

## Version

Craft version: 3.7.59
Plugin version: 3.0.12
PHP version: 7.4

**Comment by Mosnar** [comment]
Indeed - this is by design in order to prevent overhead from checking for redirects on every page load. When a 404 is triggered, Craft throws an exception, which is what triggers the plugin to kick-in and check for a valid redirect. This is definitely a bit confusing, which is why the next version of the plugin (for Craft 4) will start warning you when something may interfere with a redirect:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/3810939/201561187-86395b06-2bac-4c82-b9e3-33bbe486fbfa.png">
